package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * Habitaciones generated by hbm2java
 */
public class Habitaciones  implements java.io.Serializable {


     private int idHabitacion;
     private Hoteles hoteles;
     private Pasajeros pasajeros;
     private TipoHabitacion tipoHabitacion;
     private int nroHabitacion;
     private int nroCamas;
     private int nroBanos;
     private int nroEstrellas;
     private String estado;
     private int valorDiario;
     private Set reservaHabitacions = new HashSet(0);
     private Set promocionHabitacions = new HashSet(0);
     private Set registroInspeccions = new HashSet(0);
     private Set muebleses = new HashSet(0);

    public Habitaciones() {
        this.idHabitacion = 0;
    }

	
    public Habitaciones(int idHabitacion, Hoteles hoteles, Pasajeros pasajeros, TipoHabitacion tipoHabitacion, int nroHabitacion, int nroCamas, int nroBanos, int nroEstrellas, String estado, int valorDiario) {
        this.idHabitacion = idHabitacion;
        this.hoteles = hoteles;
        this.pasajeros = pasajeros;
        this.tipoHabitacion = tipoHabitacion;
        this.nroHabitacion = nroHabitacion;
        this.nroCamas = nroCamas;
        this.nroBanos = nroBanos;
        this.nroEstrellas = nroEstrellas;
        this.estado = estado;
        this.valorDiario = valorDiario;
    }
    public Habitaciones(int idHabitacion, Hoteles hoteles, Pasajeros pasajeros, TipoHabitacion tipoHabitacion, int nroHabitacion, int nroCamas, int nroBanos, int nroEstrellas, String estado, int valorDiario, Set reservaHabitacions, Set promocionHabitacions, Set registroInspeccions, Set muebleses) {
       this.idHabitacion = idHabitacion;
       this.hoteles = hoteles;
       this.pasajeros = pasajeros;
       this.tipoHabitacion = tipoHabitacion;
       this.nroHabitacion = nroHabitacion;
       this.nroCamas = nroCamas;
       this.nroBanos = nroBanos;
       this.nroEstrellas = nroEstrellas;
       this.estado = estado;
       this.valorDiario = valorDiario;
       this.reservaHabitacions = reservaHabitacions;
       this.promocionHabitacions = promocionHabitacions;
       this.registroInspeccions = registroInspeccions;
       this.muebleses = muebleses;
    }
   
    public int getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public Pasajeros getPasajeros() {
        return this.pasajeros;
    }
    
    public void setPasajeros(Pasajeros pasajeros) {
        this.pasajeros = pasajeros;
    }
    public TipoHabitacion getTipoHabitacion() {
        return this.tipoHabitacion;
    }
    
    public void setTipoHabitacion(TipoHabitacion tipoHabitacion) {
        this.tipoHabitacion = tipoHabitacion;
    }
    public int getNroHabitacion() {
        return this.nroHabitacion;
    }
    
    public void setNroHabitacion(int nroHabitacion) {
        this.nroHabitacion = nroHabitacion;
    }
    public int getNroCamas() {
        return this.nroCamas;
    }
    
    public void setNroCamas(int nroCamas) {
        this.nroCamas = nroCamas;
    }
    public int getNroBanos() {
        return this.nroBanos;
    }
    
    public void setNroBanos(int nroBanos) {
        this.nroBanos = nroBanos;
    }
    public int getNroEstrellas() {
        return this.nroEstrellas;
    }
    
    public void setNroEstrellas(int nroEstrellas) {
        this.nroEstrellas = nroEstrellas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getValorDiario() {
        return this.valorDiario;
    }
    
    public void setValorDiario(int valorDiario) {
        this.valorDiario = valorDiario;
    }
    public Set getReservaHabitacions() {
        return this.reservaHabitacions;
    }
    
    public void setReservaHabitacions(Set reservaHabitacions) {
        this.reservaHabitacions = reservaHabitacions;
    }
    public Set getPromocionHabitacions() {
        return this.promocionHabitacions;
    }
    
    public void setPromocionHabitacions(Set promocionHabitacions) {
        this.promocionHabitacions = promocionHabitacions;
    }
    public Set getRegistroInspeccions() {
        return this.registroInspeccions;
    }
    
    public void setRegistroInspeccions(Set registroInspeccions) {
        this.registroInspeccions = registroInspeccions;
    }
    public Set getMuebleses() {
        return this.muebleses;
    }
    
    public void setMuebleses(Set muebleses) {
        this.muebleses = muebleses;
    }




}


