package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HistorialCobro generated by hbm2java
 */
public class HistorialCobro  implements java.io.Serializable {


     private BigDecimal idCobro;
     private ReservaHabitacion reservaHabitacion;
     private BigDecimal cobro;

    public HistorialCobro() {
    }

    public HistorialCobro(BigDecimal idCobro, ReservaHabitacion reservaHabitacion, BigDecimal cobro) {
       this.idCobro = idCobro;
       this.reservaHabitacion = reservaHabitacion;
       this.cobro = cobro;
    }
   
    public BigDecimal getIdCobro() {
        return this.idCobro;
    }
    
    public void setIdCobro(BigDecimal idCobro) {
        this.idCobro = idCobro;
    }
    public ReservaHabitacion getReservaHabitacion() {
        return this.reservaHabitacion;
    }
    
    public void setReservaHabitacion(ReservaHabitacion reservaHabitacion) {
        this.reservaHabitacion = reservaHabitacion;
    }
    public BigDecimal getCobro() {
        return this.cobro;
    }
    
    public void setCobro(BigDecimal cobro) {
        this.cobro = cobro;
    }




}


