package ModeloHibernate;
// Generated 14-10-2015 20:08:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoteles generated by hbm2java
 */
public class Hoteles  implements java.io.Serializable {


     private BigDecimal idHotel;
     private String nombreHotel;
     private BigDecimal nroEstrellas;
     private String direccion;
     private BigDecimal cantidadHabitaciones;
     private Set paises = new HashSet(0);
     private Set ciudads = new HashSet(0);
     private Set menus = new HashSet(0);
     private Set serviciosExtrases = new HashSet(0);
     private Set habitacioneses = new HashSet(0);

    public Hoteles() {
    }

	
    public Hoteles(BigDecimal idHotel, String nombreHotel, BigDecimal nroEstrellas, String direccion, BigDecimal cantidadHabitaciones) {
        this.idHotel = idHotel;
        this.nombreHotel = nombreHotel;
        this.nroEstrellas = nroEstrellas;
        this.direccion = direccion;
        this.cantidadHabitaciones = cantidadHabitaciones;
    }
    public Hoteles(BigDecimal idHotel, String nombreHotel, BigDecimal nroEstrellas, String direccion, BigDecimal cantidadHabitaciones, Set paises, Set ciudads, Set menus, Set serviciosExtrases, Set habitacioneses) {
       this.idHotel = idHotel;
       this.nombreHotel = nombreHotel;
       this.nroEstrellas = nroEstrellas;
       this.direccion = direccion;
       this.cantidadHabitaciones = cantidadHabitaciones;
       this.paises = paises;
       this.ciudads = ciudads;
       this.menus = menus;
       this.serviciosExtrases = serviciosExtrases;
       this.habitacioneses = habitacioneses;
    }
   
    public BigDecimal getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(BigDecimal idHotel) {
        this.idHotel = idHotel;
    }
    public String getNombreHotel() {
        return this.nombreHotel;
    }
    
    public void setNombreHotel(String nombreHotel) {
        this.nombreHotel = nombreHotel;
    }
    public BigDecimal getNroEstrellas() {
        return this.nroEstrellas;
    }
    
    public void setNroEstrellas(BigDecimal nroEstrellas) {
        this.nroEstrellas = nroEstrellas;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getCantidadHabitaciones() {
        return this.cantidadHabitaciones;
    }
    
    public void setCantidadHabitaciones(BigDecimal cantidadHabitaciones) {
        this.cantidadHabitaciones = cantidadHabitaciones;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }
    public Set getServiciosExtrases() {
        return this.serviciosExtrases;
    }
    
    public void setServiciosExtrases(Set serviciosExtrases) {
        this.serviciosExtrases = serviciosExtrases;
    }
    public Set getHabitacioneses() {
        return this.habitacioneses;
    }
    
    public void setHabitacioneses(Set habitacioneses) {
        this.habitacioneses = habitacioneses;
    }




}


