package ModeloHibernate;
// Generated 20-10-2015 3:44:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private BigDecimal idIngrediente;
     private InventarioCocina inventarioCocina;
     private Plato plato;
     private BigDecimal cantidad;

    public Ingrediente() {
    }

    public Ingrediente(BigDecimal idIngrediente, InventarioCocina inventarioCocina, Plato plato, BigDecimal cantidad) {
       this.idIngrediente = idIngrediente;
       this.inventarioCocina = inventarioCocina;
       this.plato = plato;
       this.cantidad = cantidad;
    }
   
    public BigDecimal getIdIngrediente() {
        return this.idIngrediente;
    }
    
    public void setIdIngrediente(BigDecimal idIngrediente) {
        this.idIngrediente = idIngrediente;
    }
    public InventarioCocina getInventarioCocina() {
        return this.inventarioCocina;
    }
    
    public void setInventarioCocina(InventarioCocina inventarioCocina) {
        this.inventarioCocina = inventarioCocina;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


