package ModeloHibernate;
// Generated 13-10-2015 19:21:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Insumos generated by hbm2java
 */
public class Insumos  implements java.io.Serializable {


     private BigDecimal idInventCoc;
     private BigDecimal idInsumo;
     private String nombreInsumo;
     private BigDecimal cantidad;
     private InventarioCocina inventarioCocina;
     private Set menus = new HashSet(0);

    public Insumos() {
    }

	
    public Insumos(BigDecimal idInventCoc, BigDecimal idInsumo, String nombreInsumo, BigDecimal cantidad) {
        this.idInventCoc = idInventCoc;
        this.idInsumo = idInsumo;
        this.nombreInsumo = nombreInsumo;
        this.cantidad = cantidad;
    }
    public Insumos(BigDecimal idInventCoc, BigDecimal idInsumo, String nombreInsumo, BigDecimal cantidad, InventarioCocina inventarioCocina, Set menus) {
       this.idInventCoc = idInventCoc;
       this.idInsumo = idInsumo;
       this.nombreInsumo = nombreInsumo;
       this.cantidad = cantidad;
       this.inventarioCocina = inventarioCocina;
       this.menus = menus;
    }
   
    public BigDecimal getIdInventCoc() {
        return this.idInventCoc;
    }
    
    public void setIdInventCoc(BigDecimal idInventCoc) {
        this.idInventCoc = idInventCoc;
    }
    public BigDecimal getIdInsumo() {
        return this.idInsumo;
    }
    
    public void setIdInsumo(BigDecimal idInsumo) {
        this.idInsumo = idInsumo;
    }
    public String getNombreInsumo() {
        return this.nombreInsumo;
    }
    
    public void setNombreInsumo(String nombreInsumo) {
        this.nombreInsumo = nombreInsumo;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public InventarioCocina getInventarioCocina() {
        return this.inventarioCocina;
    }
    
    public void setInventarioCocina(InventarioCocina inventarioCocina) {
        this.inventarioCocina = inventarioCocina;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }




}


