package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventarioHabitacion generated by hbm2java
 */
public class InventarioHabitacion  implements java.io.Serializable {


     private BigDecimal idInventHab;
     private BigDecimal costoAdicional;
     private Date fechaRevision;
     private Set muebleses = new HashSet(0);

    public InventarioHabitacion() {
    }

	
    public InventarioHabitacion(BigDecimal idInventHab, BigDecimal costoAdicional, Date fechaRevision) {
        this.idInventHab = idInventHab;
        this.costoAdicional = costoAdicional;
        this.fechaRevision = fechaRevision;
    }
    public InventarioHabitacion(BigDecimal idInventHab, BigDecimal costoAdicional, Date fechaRevision, Set muebleses) {
       this.idInventHab = idInventHab;
       this.costoAdicional = costoAdicional;
       this.fechaRevision = fechaRevision;
       this.muebleses = muebleses;
    }
   
    public BigDecimal getIdInventHab() {
        return this.idInventHab;
    }
    
    public void setIdInventHab(BigDecimal idInventHab) {
        this.idInventHab = idInventHab;
    }
    public BigDecimal getCostoAdicional() {
        return this.costoAdicional;
    }
    
    public void setCostoAdicional(BigDecimal costoAdicional) {
        this.costoAdicional = costoAdicional;
    }
    public Date getFechaRevision() {
        return this.fechaRevision;
    }
    
    public void setFechaRevision(Date fechaRevision) {
        this.fechaRevision = fechaRevision;
    }
    public Set getMuebleses() {
        return this.muebleses;
    }
    
    public void setMuebleses(Set muebleses) {
        this.muebleses = muebleses;
    }




}


