package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private BigDecimal idMenu;
     private Hoteles hoteles;
     private BigDecimal precio;
     private Date fecha;
     private Set insumoses = new HashSet(0);
     private Set platos = new HashSet(0);
     private Set reservaHabitacions = new HashSet(0);

    public Menu() {
    }

	
    public Menu(BigDecimal idMenu, Hoteles hoteles, BigDecimal precio, Date fecha) {
        this.idMenu = idMenu;
        this.hoteles = hoteles;
        this.precio = precio;
        this.fecha = fecha;
    }
    public Menu(BigDecimal idMenu, Hoteles hoteles, BigDecimal precio, Date fecha, Set insumoses, Set platos, Set reservaHabitacions) {
       this.idMenu = idMenu;
       this.hoteles = hoteles;
       this.precio = precio;
       this.fecha = fecha;
       this.insumoses = insumoses;
       this.platos = platos;
       this.reservaHabitacions = reservaHabitacions;
    }
   
    public BigDecimal getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(BigDecimal idMenu) {
        this.idMenu = idMenu;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getInsumoses() {
        return this.insumoses;
    }
    
    public void setInsumoses(Set insumoses) {
        this.insumoses = insumoses;
    }
    public Set getPlatos() {
        return this.platos;
    }
    
    public void setPlatos(Set platos) {
        this.platos = platos;
    }
    public Set getReservaHabitacions() {
        return this.reservaHabitacions;
    }
    
    public void setReservaHabitacions(Set reservaHabitacions) {
        this.reservaHabitacions = reservaHabitacions;
    }




}


