package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idPerfil;
     private String tipoPerfil;
     private Set usuarios = new HashSet(0);

    public Perfil() {
        this.idPerfil=0;
    }

	
    public Perfil(int idPerfil, String tipoPerfil) {
        this.idPerfil = idPerfil;
        this.tipoPerfil = tipoPerfil;
    }
    public Perfil(int idPerfil, String tipoPerfil, Set usuarios) {
       this.idPerfil = idPerfil;
       this.tipoPerfil = tipoPerfil;
       this.usuarios = usuarios;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getTipoPerfil() {
        return this.tipoPerfil;
    }
    
    public void setTipoPerfil(String tipoPerfil) {
        this.tipoPerfil = tipoPerfil;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


