package ModeloHibernate;
// Generated 14-10-2015 20:08:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private BigDecimal idPlato;
     private Menu menu;
     private String nombrePlato;
     private Set ingredientes = new HashSet(0);

    public Plato() {
    }

	
    public Plato(BigDecimal idPlato, Menu menu, String nombrePlato) {
        this.idPlato = idPlato;
        this.menu = menu;
        this.nombrePlato = nombrePlato;
    }
    public Plato(BigDecimal idPlato, Menu menu, String nombrePlato, Set ingredientes) {
       this.idPlato = idPlato;
       this.menu = menu;
       this.nombrePlato = nombrePlato;
       this.ingredientes = ingredientes;
    }
   
    public BigDecimal getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(BigDecimal idPlato) {
        this.idPlato = idPlato;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getNombrePlato() {
        return this.nombrePlato;
    }
    
    public void setNombrePlato(String nombrePlato) {
        this.nombrePlato = nombrePlato;
    }
    public Set getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set ingredientes) {
        this.ingredientes = ingredientes;
    }




}


