package ModeloHibernate;
// Generated 20-10-2015 3:44:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PromocionHabitacion generated by hbm2java
 */
public class PromocionHabitacion  implements java.io.Serializable {


     private BigDecimal idPromocion;
     private Habitaciones habitaciones;
     private BigDecimal procentajeDescuento;

    public PromocionHabitacion() {
    }

    public PromocionHabitacion(BigDecimal idPromocion, Habitaciones habitaciones, BigDecimal procentajeDescuento) {
       this.idPromocion = idPromocion;
       this.habitaciones = habitaciones;
       this.procentajeDescuento = procentajeDescuento;
    }
   
    public BigDecimal getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(BigDecimal idPromocion) {
        this.idPromocion = idPromocion;
    }
    public Habitaciones getHabitaciones() {
        return this.habitaciones;
    }
    
    public void setHabitaciones(Habitaciones habitaciones) {
        this.habitaciones = habitaciones;
    }
    public BigDecimal getProcentajeDescuento() {
        return this.procentajeDescuento;
    }
    
    public void setProcentajeDescuento(BigDecimal procentajeDescuento) {
        this.procentajeDescuento = procentajeDescuento;
    }




}


