package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private BigDecimal idProveedor;
     private Ciudad ciudad;
     private Pais pais;
     private String rutProveedor;
     private String nombreProveedor;
     private BigDecimal telefono;
     private String direccion;
     private String email;
     private Date fechaRegistro;
     private Set inventarioCocinas = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(BigDecimal idProveedor, Ciudad ciudad, Pais pais, String rutProveedor, String nombreProveedor, BigDecimal telefono, String direccion, String email, Date fechaRegistro) {
        this.idProveedor = idProveedor;
        this.ciudad = ciudad;
        this.pais = pais;
        this.rutProveedor = rutProveedor;
        this.nombreProveedor = nombreProveedor;
        this.telefono = telefono;
        this.direccion = direccion;
        this.email = email;
        this.fechaRegistro = fechaRegistro;
    }
    public Proveedores(BigDecimal idProveedor, Ciudad ciudad, Pais pais, String rutProveedor, String nombreProveedor, BigDecimal telefono, String direccion, String email, Date fechaRegistro, Set inventarioCocinas) {
       this.idProveedor = idProveedor;
       this.ciudad = ciudad;
       this.pais = pais;
       this.rutProveedor = rutProveedor;
       this.nombreProveedor = nombreProveedor;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.fechaRegistro = fechaRegistro;
       this.inventarioCocinas = inventarioCocinas;
    }
   
    public BigDecimal getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(BigDecimal idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getRutProveedor() {
        return this.rutProveedor;
    }
    
    public void setRutProveedor(String rutProveedor) {
        this.rutProveedor = rutProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getInventarioCocinas() {
        return this.inventarioCocinas;
    }
    
    public void setInventarioCocinas(Set inventarioCocinas) {
        this.inventarioCocinas = inventarioCocinas;
    }




}


