package ModeloHibernate;
// Generated 14-10-2015 20:08:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReservaHabitacion generated by hbm2java
 */
public class ReservaHabitacion  implements java.io.Serializable {


     private BigDecimal idResHab;
     private Habitaciones habitaciones;
     private Usuario usuario;
     private BigDecimal precioTotal;
     private Date fechaInicio;
     private Date fechaTermino;
     private Set reservaServExts = new HashSet(0);
     private Set historialCobros = new HashSet(0);
     private Set menus = new HashSet(0);

    public ReservaHabitacion() {
    }

	
    public ReservaHabitacion(BigDecimal idResHab, Habitaciones habitaciones, Usuario usuario, BigDecimal precioTotal, Date fechaInicio, Date fechaTermino) {
        this.idResHab = idResHab;
        this.habitaciones = habitaciones;
        this.usuario = usuario;
        this.precioTotal = precioTotal;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
    }
    public ReservaHabitacion(BigDecimal idResHab, Habitaciones habitaciones, Usuario usuario, BigDecimal precioTotal, Date fechaInicio, Date fechaTermino, Set reservaServExts, Set historialCobros, Set menus) {
       this.idResHab = idResHab;
       this.habitaciones = habitaciones;
       this.usuario = usuario;
       this.precioTotal = precioTotal;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.reservaServExts = reservaServExts;
       this.historialCobros = historialCobros;
       this.menus = menus;
    }
   
    public BigDecimal getIdResHab() {
        return this.idResHab;
    }
    
    public void setIdResHab(BigDecimal idResHab) {
        this.idResHab = idResHab;
    }
    public Habitaciones getHabitaciones() {
        return this.habitaciones;
    }
    
    public void setHabitaciones(Habitaciones habitaciones) {
        this.habitaciones = habitaciones;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public Set getReservaServExts() {
        return this.reservaServExts;
    }
    
    public void setReservaServExts(Set reservaServExts) {
        this.reservaServExts = reservaServExts;
    }
    public Set getHistorialCobros() {
        return this.historialCobros;
    }
    
    public void setHistorialCobros(Set historialCobros) {
        this.historialCobros = historialCobros;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }




}


