package ModeloHibernate;
// Generated 13-10-2015 19:21:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReservaServExt generated by hbm2java
 */
public class ReservaServExt  implements java.io.Serializable {


     private BigDecimal idResServ;
     private ReservaHabitacion reservaHabitacion;
     private Date fechaResServ;
     private Set serviciosExtrases = new HashSet(0);

    public ReservaServExt() {
    }

	
    public ReservaServExt(BigDecimal idResServ, ReservaHabitacion reservaHabitacion, Date fechaResServ) {
        this.idResServ = idResServ;
        this.reservaHabitacion = reservaHabitacion;
        this.fechaResServ = fechaResServ;
    }
    public ReservaServExt(BigDecimal idResServ, ReservaHabitacion reservaHabitacion, Date fechaResServ, Set serviciosExtrases) {
       this.idResServ = idResServ;
       this.reservaHabitacion = reservaHabitacion;
       this.fechaResServ = fechaResServ;
       this.serviciosExtrases = serviciosExtrases;
    }
   
    public BigDecimal getIdResServ() {
        return this.idResServ;
    }
    
    public void setIdResServ(BigDecimal idResServ) {
        this.idResServ = idResServ;
    }
    public ReservaHabitacion getReservaHabitacion() {
        return this.reservaHabitacion;
    }
    
    public void setReservaHabitacion(ReservaHabitacion reservaHabitacion) {
        this.reservaHabitacion = reservaHabitacion;
    }
    public Date getFechaResServ() {
        return this.fechaResServ;
    }
    
    public void setFechaResServ(Date fechaResServ) {
        this.fechaResServ = fechaResServ;
    }
    public Set getServiciosExtrases() {
        return this.serviciosExtrases;
    }
    
    public void setServiciosExtrases(Set serviciosExtrases) {
        this.serviciosExtrases = serviciosExtrases;
    }




}


