package ModeloHibernate;
// Generated 14-10-2015 20:08:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiciosExtras generated by hbm2java
 */
public class ServiciosExtras  implements java.io.Serializable {


     private BigDecimal idServExt;
     private Hoteles hoteles;
     private String nombreServExt;
     private BigDecimal valorDiario;
     private Set reservaServExts = new HashSet(0);

    public ServiciosExtras() {
    }

	
    public ServiciosExtras(BigDecimal idServExt, Hoteles hoteles, String nombreServExt, BigDecimal valorDiario) {
        this.idServExt = idServExt;
        this.hoteles = hoteles;
        this.nombreServExt = nombreServExt;
        this.valorDiario = valorDiario;
    }
    public ServiciosExtras(BigDecimal idServExt, Hoteles hoteles, String nombreServExt, BigDecimal valorDiario, Set reservaServExts) {
       this.idServExt = idServExt;
       this.hoteles = hoteles;
       this.nombreServExt = nombreServExt;
       this.valorDiario = valorDiario;
       this.reservaServExts = reservaServExts;
    }
   
    public BigDecimal getIdServExt() {
        return this.idServExt;
    }
    
    public void setIdServExt(BigDecimal idServExt) {
        this.idServExt = idServExt;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public String getNombreServExt() {
        return this.nombreServExt;
    }
    
    public void setNombreServExt(String nombreServExt) {
        this.nombreServExt = nombreServExt;
    }
    public BigDecimal getValorDiario() {
        return this.valorDiario;
    }
    
    public void setValorDiario(BigDecimal valorDiario) {
        this.valorDiario = valorDiario;
    }
    public Set getReservaServExts() {
        return this.reservaServExts;
    }
    
    public void setReservaServExts(Set reservaServExts) {
        this.reservaServExts = reservaServExts;
    }




}


