package ModeloHibernate;
// Generated 19-10-2015 19:45:52 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * ServiciosExtras generated by hbm2java
 */
public class ServiciosExtras  implements java.io.Serializable {


     private int idServExt;
     private Hoteles hoteles;
     private String nombreServExt;
     private int valorDiario;
     private Set reservaServExts = new HashSet(0);

    public ServiciosExtras() {
        this.idServExt = 0;
        this.hoteles = new Hoteles();
    }

	
    public ServiciosExtras(int idServExt, Hoteles hoteles, String nombreServExt, int valorDiario) {
        this.idServExt = idServExt;
        this.hoteles = hoteles;
        this.nombreServExt = nombreServExt;
        this.valorDiario = valorDiario;
    }
    public ServiciosExtras(int idServExt, Hoteles hoteles, String nombreServExt, int valorDiario, Set reservaServExts) {
       this.idServExt = idServExt;
       this.hoteles = hoteles;
       this.nombreServExt = nombreServExt;
       this.valorDiario = valorDiario;
       this.reservaServExts = reservaServExts;
    }
   
    public int getIdServExt() {
        return this.idServExt;
    }
    
    public void setIdServExt(int idServExt) {
        this.idServExt = idServExt;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public String getNombreServExt() {
        return this.nombreServExt;
    }
    
    public void setNombreServExt(String nombreServExt) {
        this.nombreServExt = nombreServExt;
    }
    public int getValorDiario() {
        return this.valorDiario;
    }
    
    public void setValorDiario(int valorDiario) {
        this.valorDiario = valorDiario;
    }
    public Set getReservaServExts() {
        return this.reservaServExts;
    }
    
    public void setReservaServExts(Set reservaServExts) {
        this.reservaServExts = reservaServExts;
    }




}


