package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * TipoHabitacion generated by hbm2java
 */
public class TipoHabitacion  implements java.io.Serializable {


     private int idTipoHab;
     private String nombreTipo;
     private int valorDiario;
     private Set habitacioneses = new HashSet(0);

    public TipoHabitacion() {
        this.idTipoHab = 0;
    }

	
    public TipoHabitacion(int idTipoHab, String nombreTipo, int valorDiario) {
        this.idTipoHab = idTipoHab;
        this.nombreTipo = nombreTipo;
        this.valorDiario = valorDiario;
    }
    public TipoHabitacion(int idTipoHab, String nombreTipo, int valorDiario, Set habitacioneses) {
       this.idTipoHab = idTipoHab;
       this.nombreTipo = nombreTipo;
       this.valorDiario = valorDiario;
       this.habitacioneses = habitacioneses;
    }
   
    public int getIdTipoHab() {
        return this.idTipoHab;
    }
    
    public void setIdTipoHab(int idTipoHab) {
        this.idTipoHab = idTipoHab;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public int getValorDiario() {
        return this.valorDiario;
    }
    
    public void setValorDiario(int valorDiario) {
        this.valorDiario = valorDiario;
    }
    public Set getHabitacioneses() {
        return this.habitacioneses;
    }
    
    public void setHabitacioneses(Set habitacioneses) {
        this.habitacioneses = habitacioneses;
    }




}


