package ModeloHibernate;
// Generated 20-10-2015 20:40:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Perfil perfil;
     private String rutUsuario;
     private String nombreUsuario;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String sexo;
     private String nacionalidad;
     private String residenciaActual;
     private Date fechaNacimiento;
     private String regionNacimiento;
     private int telefono;
     private String email;
     private String contraUsuario;
     private Set descuentos = new HashSet(0);
     private Set reservaHabitacions = new HashSet(0);

    public Usuario() {
        this.idUsuario = 0;
        this.perfil = new Perfil();
    }

	
    public Usuario(int idUsuario, Perfil perfil, String rutUsuario, String nombreUsuario, String apellidoPaterno, String apellidoMaterno, String sexo, String nacionalidad, String residenciaActual, Date fechaNacimiento, String regionNacimiento, int telefono, String email, String contraUsuario) {
        this.idUsuario = idUsuario;
        this.perfil = perfil;
        this.rutUsuario = rutUsuario;
        this.nombreUsuario = nombreUsuario;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.sexo = sexo;
        this.nacionalidad = nacionalidad;
        this.residenciaActual = residenciaActual;
        this.fechaNacimiento = fechaNacimiento;
        this.regionNacimiento = regionNacimiento;
        this.telefono = telefono;
        this.email = email;
        this.contraUsuario = contraUsuario;
    }
    public Usuario(int idUsuario, Perfil perfil, String rutUsuario, String nombreUsuario, String apellidoPaterno, String apellidoMaterno, String sexo, String nacionalidad, String residenciaActual, Date fechaNacimiento, String regionNacimiento, int telefono, String email, String contraUsuario, Set descuentos, Set reservaHabitacions) {
       this.idUsuario = idUsuario;
       this.perfil = perfil;
       this.rutUsuario = rutUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.sexo = sexo;
       this.nacionalidad = nacionalidad;
       this.residenciaActual = residenciaActual;
       this.fechaNacimiento = fechaNacimiento;
       this.regionNacimiento = regionNacimiento;
       this.telefono = telefono;
       this.email = email;
       this.contraUsuario = contraUsuario;
       this.descuentos = descuentos;
       this.reservaHabitacions = reservaHabitacions;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getRutUsuario() {
        return this.rutUsuario;
    }
    
    public void setRutUsuario(String rutUsuario) {
        this.rutUsuario = rutUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getResidenciaActual() {
        return this.residenciaActual;
    }
    
    public void setResidenciaActual(String residenciaActual) {
        this.residenciaActual = residenciaActual;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getRegionNacimiento() {
        return this.regionNacimiento;
    }
    
    public void setRegionNacimiento(String regionNacimiento) {
        this.regionNacimiento = regionNacimiento;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContraUsuario() {
        return this.contraUsuario;
    }
    
    public void setContraUsuario(String contraUsuario) {
        this.contraUsuario = contraUsuario;
    }
    public Set getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Set descuentos) {
        this.descuentos = descuentos;
    }
    public Set getReservaHabitacions() {
        return this.reservaHabitacions;
    }
    
    public void setReservaHabitacions(Set reservaHabitacions) {
        this.reservaHabitacions = reservaHabitacions;
    }




}


